require 'html-proofer'

task :test do
  sh 'bundle exec jekyll build'
  HTMLProofer.check_directory('./_site', {
    :url_ignore => [/linkedin.com/, /twitter.com/, /x.com/, /facebook.com/, /fonts.googleapis.com/, /fonts.gstatic.com/],
    # Note that https://x.com/rubycon2026 doesnt work
    :enforce_https => true,
    :check_external_hash => true,
    :check_html => true,
    :check_img_http => true,
    :check_opengraph => true,
    :check_twitter_card => true,
    :assume_extension => true,
    :empty_alt_ignore => true,
    :disable_external => false, # check external links
    :typhoeus => {
      :timeout => 30,
      :connecttimeout => 10,
      :followlocation => true
    },
    :hydra => { :max_concurrency => 5 } # Reduce concurrency to avoid rate limiting
  }).run
end
