name: Auto Merge issue36 into main

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge issue36 into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/issue36 --no-edit
          git push origin main
